steps:
  # Крок збірки Docker-зображення
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/jfiweht23ub/ddd-libra', '.']
images:
  - 'gcr.io/$PROJECT_ID/redis'
  - 'gcr.io/$PROJECT_ID/postgres'
  - 'gcr.io/$PROJECT_ID/library_platform_ddd-main'
  # Крок розгортання на Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'ddd-libra', '--image', 'gcr.io/$PROJECT_ID/jfiweht23ub/ddd-libra', '--platform', 'managed', '--region', 'us-west2']
